[package]
name = "picomq-connector-mongodb-sink"
version.workspace = true
description = "PicoMQ MongoDB sink connector for storing stream messages into MongoDB database"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "picomq_connector_mongodb_sink"
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait = { workspace = true }
humantime = { workspace = true }
picomq-connector-sdk = { path = "../../sdk" }
mongodb = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
missing_safety_doc = "allow"
