[package]
name = "picomq-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "PicoMQ CLI: the `pico` binary"
repository.workspace = true

[[bin]]
name = "pico"
path = "src/main.rs"

[dependencies]
s3stream = { workspace = true }
picomq-auth = { workspace = true }
picomq-http = { workspace = true }
picomq-runtime = { workspace = true }
picomq-client = { workspace = true }
bytes = { workspace = true }
hdrhistogram = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }

clap = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing-subscriber = { workspace = true }
rdkafka = { workspace = true }
keyring = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
